---
---
title: "Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import des library

```{r message = FALSE}
library(tidyverse)
library(reshape2)
library(ggthemes)

```

## Import des données

```{r message = FALSE}
world_region_data <- read_delim("data/World_Region_Data/world_region_data.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

world_region_data2 <- read_delim("data/World_Region_Data/world_region_data2.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

world_country_data1 <- read_delim("data/World_Country_Data/world_country_data1.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

world_country_data2 <- read_delim("data/World_Country_Data/world_country_data2.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

world_country_data3 <- read_delim("data/World_Country_Data/world_country_data3.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
```

## Agrégation des datasets

```{r}
region_dataset <- merge(x = world_region_data, y = world_region_data2, by = "Year", all = TRUE)
region_dataset <- data.frame(region_dataset)
region_dataset <- tibble(region_dataset)

merged1 <- merge(x = world_country_data1, y = world_country_data2, by = "Year", all = TRUE)
country_dataset <- merge(x = merged1, y = world_country_data3, by = "Year", all = TRUE)
country_dataset <- data.frame(country_dataset)
country_dataset <- tibble(country_dataset)
```

## Création de sous-datasets pour séparer les données par indicateurs

```{r}
NIdataset <- region_dataset %>% select("Year", ends_with("NI"))
GDPdataset <- region_dataset %>% select("Year", ends_with("GDP"))
PTNIB40dataset <- region_dataset %>% select("Year", ends_with("PTNIB40"))
PTNIB50dataset <- region_dataset %>% select("Year", ends_with("PTNIB50"))
PTNIT1dataset <- region_dataset %>% select("Year", ends_with("PTNIT1"))
PTNIT10dataset <- region_dataset %>% select("Year", ends_with("PTNIT10"))
PTNIM40dataset <- region_dataset %>% select("Year", ends_with("PTNIM40"))
```


```{r}
# Traitement du dataset PTNIT10 et PTNIB40
tempdataset <- PTNIT10dataset %>% rename("World"=WorldPTNIT10,"Western Europe"=WesternEuropePTNIT10, Asia=AsiaPTNIT10, "Eastern Europe"=EasternEuropePTNIT10, "Northern America"=NorthernAmericaPTNIT10, Oceania=OceaniaPTNIT10, "Latin America"=LatinAmericaPTNIT10, Africa=AfricaPTNIT10) %>%
melt(id.vars="Year") %>%
filter(variable=="World"|variable=="Western Europe"|variable=="Asia"|variable=="Eastern Europe"|variable=="Northern America"|variable=="Oceania"|variable=="Latin America"|variable=="Africa")%>%
mutate(PTNIT10_in_percent = value*100)%>%
subset (select = -value)

tempdataset2 <- PTNIM40dataset %>% rename("World"=WorldPTNIM40,"Western Europe"=WesternEuropePTNIM40, Asia=AsiaPTNIM40, "Eastern Europe"=EasternEuropePTNIM40, "Northern America"=NorthernAmericaPTNIM40, Oceania=OceaniaPTNIM40, "Latin America"=LatinAmericaPTNIM40, Africa=AfricaPTNIM40) %>%
melt(id.vars="Year") %>%
filter(variable=="World"|variable=="Western Europe"|variable=="Asia"|variable=="Eastern Europe"|variable=="Northern America"|variable=="Oceania"|variable=="Latin America"|variable=="Africa") %>%
mutate(PTNIM40_in_percent = value*100)%>%
subset (select = -value)


tempdataset3 <- PTNIB50dataset %>% rename("World"=WorldPTNIB50,"Western Europe"=WesternEuropePTNIB50, Asia=AsiaPTNIB50, "Eastern Europe"=EasternEuropePTNIB50, "Northern America"=NorthernAmericaPTNIB50, Oceania=OceaniaPTNIB50, "Latin America"=LatinAmericaPTNIB50, Africa=AfricaPTNIB50) %>%
melt(id.vars="Year") %>%
filter(variable=="World"|variable=="Western Europe"|variable=="Asia"|variable=="Eastern Europe"|variable=="Northern America"|variable=="Oceania"|variable=="Latin America"|variable=="Africa") %>%
mutate(PTNIB50_in_percent = value*100)%>%
subset (select = -value)

tempdataset4 <- PTNIT1dataset %>% rename("World"=WorldPTNIT1,"Western Europe"=WesternEuropePTNIT1, Asia=AsiaPTNIT1, "Eastern Europe"=EasternEuropePTNIT1, "Northern America"=NorthernAmericaPTNIT1, Oceania=OceaniaPTNIT1, "Latin America"=LatinAmericaPTNIT1, Africa=AfricaPTNIT1) %>%
melt(id.vars="Year") %>%
filter(variable=="World"|variable=="Western Europe"|variable=="Asia"|variable=="Eastern Europe"|variable=="Northern America"|variable=="Oceania"|variable=="Latin America"|variable=="Africa")%>%
mutate(PTNIT1_in_percent = value*100)%>%
subset (select = -value)

tempdataset5 <- NIdataset %>% rename("World"=WorldNI,"Western Europe"=WesternEuropeNI, Asia=AsiaNI, "Eastern Europe"=EasternEuropeNI, "Northern America"=NorthernAmericaNI, Oceania=OceaniaNI, "Latin America"=LatinAmericaNI, Africa=AfricaNI) %>%
melt(id.vars="Year") %>%
filter(variable=="World"|variable=="Western Europe"|variable=="Asia"|variable=="Eastern Europe"|variable=="Northern America"|variable=="Oceania"|variable=="Latin America"|variable=="Africa")%>%
rename(NI=value)

tempdataset6 <- GDPdataset %>% rename("World"=WorldGDP,"Western Europe"=WesternEuropeGDP, Asia=AsiaGDP, "Eastern Europe"=EasternEuropeGDP, "Northern America"=NorthernAmericaGDP, Oceania=OceaniaGDP, "Latin America"=LatinAmericaGDP, Africa=AfricaGDP) %>%
melt(id.vars="Year") %>%
filter(variable=="World"|variable=="Western Europe"|variable=="Asia"|variable=="Eastern Europe"|variable=="Northern America"|variable=="Oceania"|variable=="Latin America"|variable=="Africa")%>%
rename(GDP=value)
```

```{r}
final_region_dataset <- merge(x = tempdataset, y = tempdataset2, by = c("Year", "variable"), all = TRUE)
final_region_dataset <- merge(x = final_region_dataset, y = tempdataset3, by = c("Year", "variable"), all = TRUE)
final_region_dataset <- merge(x = final_region_dataset, y = tempdataset4, by = c("Year", "variable"), all = TRUE)
final_region_dataset <- merge(x = final_region_dataset, y = tempdataset5, by = c("Year", "variable"), all = TRUE)
final_region_dataset <- merge(x = final_region_dataset, y = tempdataset6, by = c("Year", "variable"), all = TRUE)%>%
rename(Region=variable)

```

```{r}
PatGouvdataset <- world_country_data1 %>% select("Year", ends_with("PatrimoineGouvernement"))
PatPrivdataset <- world_country_data1 %>% select("Year", ends_with("PatrimoinePrivé"))
PIBdataset <- world_country_data1 %>% select("Year", ends_with("PIB"))
RatioPatRevdataset <- world_country_data1 %>% select("Year", ends_with("RatioPatrimoineRevenu"))
RevNatdataset <- world_country_data2 %>% select("Year", ends_with("RevenuNational"))
RevNatTop10dataset <- world_country_data2 %>% select("Year", ends_with("RevenuNationalPT(Top10%)"))
RevNatBottom50dataset <- world_country_data2 %>% select("Year", ends_with("RevenuNationalPT(Bottom50%)"))
RevNatTop1dataset <- world_country_data2 %>% select("Year", ends_with("RevenuNationalPT(Top1%)"))
RevNatMedium40dataset <- world_country_data2 %>% select("Year", ends_with("RevenuNationalPT(Medium40%)"))
CapNatdataset <- world_country_data3 %>% select("Year", ends_with("CapitalNational"))
PatTop10 <- country_dataset %>% select("Year", ends_with("Patrimoine.Top10.."))
PatMedium40 <- country_dataset %>% select("Year", ends_with("Patrimoine.Medium40.."))
PatBottom50 <- country_dataset %>% select("Year", ends_with("Patrimoine.Bottom50.."))
PatTop1 <- country_dataset %>% select("Year", ends_with("Patrimoine.Top1.."))

tempdataset <- PatGouvdataset %>% rename("France"=France_PatrimoineGouvernement,"Afrique du Sud"=AfriqueSud_PatrimoineGouvernement, "Australie"=Australie_PatrimoineGouvernement, "Canada"=Canada_PatrimoineGouvernement, "Chine"=Chine_PatrimoineGouvernement, "Danemark"=Danemark_PatrimoineGouvernement, "Inde"=Inde_PatrimoineGouvernement, "Royaume-Uni"=RU_PatrimoineGouvernement, "Japon"=Japon_PatrimoineGouvernement, "Mexique"=Mexique_PatrimoineGouvernement, "Russie"=Russie_PatrimoineGouvernement, "Etats-Unis"=US_PatrimoineGouvernement) %>%
melt(id.vars="Year") %>%
mutate(PatrimoineGouvernement = value)%>%
subset (select = -value)

tempdataset2 <- PatPrivdataset %>% rename("France"=France_PatrimoinePrivé,"Afrique du Sud"=AfriqueSud_PatrimoinePrivé, "Australie"=Australie_PatrimoinePrivé, "Canada"=Canada_PatrimoinePrivé, "Chine"=Chine_PatrimoinePrivé, "Danemark"=Danemark_PatrimoinePrivé, "Inde"=Inde_PatrimoinePrivé, "Royaume-Uni"=RU_PatrimoinePrivé, "Japon"=Japon_PatrimoinePrivé, "Mexique"=Mexique_PatrimoinePrivé, "Russie"=Russie_PatrimoinePrivé, "Etats-Unis"=US_PatrimoinePrivé) %>%
melt(id.vars="Year") %>%
mutate(PatrimoinePrivé = value)%>%
subset (select = -value)

tempdataset3 <- PIBdataset %>% rename("France"=France_PIB,"Afrique du Sud"=AfriqueSud_PIB, "Australie"=Australie_PIB, "Canada"=Canada_PIB, "Chine"=Chine_PIB, "Danemark"=Danemark_PIB, "Inde"=Inde_PIB, "Royaume-Uni"=RU_PIB, "Japon"=Japon_PIB, "Mexique"=Mexique_PIB, "Russie"=Russie_PIB, "Etats-Unis"=US_PIB) %>%
melt(id.vars="Year") %>%
mutate(PIB = value)%>%
subset (select = -value)

tempdataset4 <- RatioPatRevdataset %>% rename("France"=France_RatioPatrimoineRevenu,"Afrique du Sud"=AfriqueSud_RatioPatrimoineRevenu, "Australie"=Australie_RatioPatrimoineRevenu, "Canada"=Canada_RatioPatrimoineRevenu, "Chine"=Chine_RatioPatrimoineRevenu, "Danemark"=Danemark_RatioPatrimoineRevenu, "Inde"=Inde_RatioPatrimoineRevenu, "Royaume-Uni"=RU_RatioPatrimoineRevenu, "Japon"=Japon_RatioPatrimoineRevenu, "Mexique"=Mexique_RatioPatrimoineRevenu, "Russie"=Russie_RatioPatrimoineRevenu, "Etats-Unis"=US_RatioPatrimoineRevenu) %>%
melt(id.vars="Year") %>%
mutate(RatioPatrimoineRevenu = value)%>%
subset (select = -value)

tempdataset5 <- RevNatdataset %>% rename("France"=France_RevenuNational,"Afrique du Sud"=AfriqueSud_RevenuNational, "Australie"=Australie_RevenuNational, "Canada"=Canada_RevenuNational, "Chine"=Chine_RevenuNational, "Danemark"=Danemark_RevenuNational, "Inde"=Inde_RevenuNational, "Royaume-Uni"=RU_RevenuNational, "Japon"=Japon_RevenuNational, "Mexique"=Mexique_RevenuNational, "Russie"=Russie_RevenuNational, "Etats-Unis"=US_RevenuNational) %>%
melt(id.vars="Year") %>%
mutate(RevenuNational = value)%>%
subset (select = -value)

tempdataset6 <- RevNatTop10dataset %>% rename("France"=`France_RevenuNationalPT(Top10%)`,"Afrique du Sud"=`AfriqueSud_RevenuNationalPT(Top10%)`, "Australie"=`Australie_RevenuNationalPT(Top10%)`, "Canada"=`Canada_RevenuNationalPT(Top10%)`, "Chine"=`Chine_RevenuNationalPT(Top10%)`, "Danemark"=`Danemark_RevenuNationalPT(Top10%)`, "Inde"=`Inde_RevenuNationalPT(Top10%)`, "Royaume-Uni"=`RU_RevenuNationalPT(Top10%)`, "Japon"=`Japon_RevenuNationalPT(Top10%)`, "Mexique"=`Mexique_RevenuNationalPT(Top10%)`, "Russie"=`Russie_RevenuNationalPT(Top10%)`, "Etats-Unis"=`US_RevenuNationalPT(Top10%)`) %>%
melt(id.vars="Year") %>%
mutate(RevenuNationalTop10 = value*100)%>%
subset (select = -value)

tempdataset7 <- RevNatBottom50dataset %>% rename("France"=`France_RevenuNationalPT(Bottom50%)`,"Afrique du Sud"=`AfriqueSud_RevenuNationalPT(Bottom50%)`, "Australie"=`Australie_RevenuNationalPT(Bottom50%)`, "Canada"=`Canada_RevenuNationalPT(Bottom50%)`, "Chine"=`Chine_RevenuNationalPT(Bottom50%)`, "Danemark"=`Danemark_RevenuNationalPT(Bottom50%)`, "Inde"=`Inde_RevenuNationalPT(Bottom50%)`, "Royaume-Uni"=`RU_RevenuNationalPT(Bottom50%)`, "Japon"=`Japon_RevenuNationalPT(Bottom50%)`, "Mexique"=`Mexique_RevenuNationalPT(Bottom50%)`, "Russie"=`Russie_RevenuNationalPT(Bottom50%)`, "Etats-Unis"=`US_RevenuNationalPT(Bottom50%)`) %>%
melt(id.vars="Year") %>%
mutate(RevenuNationalBottom50 = value*100)%>%
subset (select = -value)

tempdataset8 <- RevNatTop1dataset %>% rename("France"=`France_RevenuNationalPT(Top1%)`,"Afrique du Sud"=`AfriqueSud_RevenuNationalPT(Top1%)`, "Australie"=`Australie_RevenuNationalPT(Top1%)`, "Canada"=`Canada_RevenuNationalPT(Top1%)`, "Chine"=`Chine_RevenuNationalPT(Top1%)`, "Danemark"=`Danemark_RevenuNationalPT(Top1%)`, "Inde"=`Inde_RevenuNationalPT(Top1%)`, "Royaume-Uni"=`RU_RevenuNationalPT(Top1%)`, "Japon"=`Japon_RevenuNationalPT(Top1%)`, "Mexique"=`Mexique_RevenuNationalPT(Top1%)`, "Russie"=`Russie_RevenuNationalPT(Top1%)`, "Etats-Unis"=`US_RevenuNationalPT(Top1%)`) %>%
melt(id.vars="Year") %>%
mutate(RevenuNationalTop1 = value*100)%>%
subset (select = -value)

tempdataset9 <- RevNatMedium40dataset %>% rename("France"=`France_RevenuNationalPT(Medium40%)`,"Afrique du Sud"=`AfriqueSud_RevenuNationalPT(Medium40%)`, "Australie"=`Australie_RevenuNationalPT(Medium40%)`, "Canada"=`Canada_RevenuNationalPT(Medium40%)`, "Chine"=`Chine_RevenuNationalPT(Medium40%)`, "Danemark"=`Danemark_RevenuNationalPT(Medium40%)`, "Inde"=`Inde_RevenuNationalPT(Medium40%)`, "Royaume-Uni"=`RU_RevenuNationalPT(Medium40%)`, "Japon"=`Japon_RevenuNationalPT(Medium40%)`, "Mexique"=`Mexique_RevenuNationalPT(Medium40%)`, "Russie"=`Russie_RevenuNationalPT(Medium40%)`, "Etats-Unis"=`US_RevenuNationalPT(Medium40%)`) %>%
melt(id.vars="Year") %>%
mutate(RevenuNationalMedium40 = value*100)%>%
subset (select = -value)

tempdataset10 <- CapNatdataset %>% rename("France"=France_CapitalNational,"Afrique du Sud"=AfriqueSud_CapitalNational, "Australie"=Australie_CapitalNational, "Canada"=Canada_CapitalNational, "Chine"=Chine_CapitalNational, "Danemark"=Danemark_CapitalNational, "Inde"=Inde_CapitalNational, "Royaume-Uni"=RU_CapitalNational, "Japon"=Japon_CapitalNational, "Mexique"=Mexique_CapitalNational, "Russie"=Russie_CapitalNational, "Etats-Unis"=US_CapitalNational) %>%
melt(id.vars="Year") %>%
mutate(CapitalNational = value*100)%>%
subset (select = -value)

tempdataset11 <- PatTop10 %>% rename("France"=France_Patrimoine.Top10..,"Afrique du Sud"=AfriqueSud_Patrimoine.Top10.., "Australie"=Australie_Patrimoine.Top10.., "Canada"=Canada_Patrimoine.Top10.., "Chine"=Chine_Patrimoine.Top10.., "Danemark"=Danemark_Patrimoine.Top10.., "Inde"=Inde_Patrimoine.Top10.., "Royaume-Uni"=RU_Patrimoine.Top10.., "Japon"=Japon_Patrimoine.Top10.., "Mexique"=Mexique_Patrimoine.Top10.., "Russie"=Russie_Patrimoine.Top10.., "Etats-Unis"=US_Patrimoine.Top10..) %>%
melt(id.vars="Year") %>%
mutate(PatrimoineTop10 = value*100)%>%
subset (select = -value)

tempdataset12 <- PatBottom50 %>% rename("France"=France_Patrimoine.Bottom50..,"Afrique du Sud"=AfriqueSud_Patrimoine.Bottom50.., "Australie"=Australie_Patrimoine.Bottom50.., "Canada"=Canada_Patrimoine.Bottom50.., "Chine"=Chine_Patrimoine.Bottom50.., "Danemark"=Danemark_Patrimoine.Bottom50.., "Inde"=Inde_Patrimoine.Bottom50.., "Royaume-Uni"=RU_Patrimoine.Bottom50.., "Japon"=Japon_Patrimoine.Bottom50.., "Mexique"=Mexique_Patrimoine.Bottom50.., "Russie"=Russie_Patrimoine.Bottom50.., "Etats-Unis"=US_Patrimoine.Bottom50..) %>%
melt(id.vars="Year") %>%
mutate(PatrimoineBottom50 = value*100)%>%
subset (select = -value)

tempdataset13 <- PatTop1 %>% rename("France"=France_Patrimoine.Top1..,"Afrique du Sud"=AfriqueSud_Patrimoine.Top1.., "Australie"=Australie_Patrimoine.Top1.., "Canada"=Canada_Patrimoine.Top1.., "Chine"=Chine_Patrimoine.Top1.., "Danemark"=Danemark_Patrimoine.Top1.., "Inde"=Inde_Patrimoine.Top1.., "Royaume-Uni"=RU_Patrimoine.Top1.., "Japon"=Japon_Patrimoine.Top1.., "Mexique"=Mexique_Patrimoine.Top1.., "Russie"=Russie_Patrimoine.Top1.., "Etats-Unis"=US_Patrimoine.Top1..) %>%
melt(id.vars="Year") %>%
mutate(PatrimoineTop1 = value*100)%>%
subset (select = -value)

tempdataset14 <- PatMedium40 %>% rename("France"=France_Patrimoine.Medium40..,"Afrique du Sud"=AfriqueSud_Patrimoine.Medium40.., "Australie"=Australie_Patrimoine.Medium40.., "Canada"=Canada_Patrimoine.Medium40.., "Chine"=Chine_Patrimoine.Medium40.., "Danemark"=Danemark_Patrimoine.Medium40.., "Inde"=Inde_Patrimoine.Medium40.., "Royaume-Uni"=RU_Patrimoine.Medium40.., "Japon"=Japon_Patrimoine.Medium40.., "Mexique"=Mexique_Patrimoine.Medium40.., "Russie"=Russie_Patrimoine.Medium40.., "Etats-Unis"=US_Patrimoine.Medium40..) %>%
melt(id.vars="Year") %>%
mutate(PatrimoineMedium40 = value*100)%>%
subset (select = -value)

final_country_dataset <- merge(x = tempdataset, y = tempdataset2, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset3, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset4, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset5, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset6, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset7, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset8, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset9, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset10, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset11, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset12, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset13, by = c("Year", "variable"), all = TRUE)
final_country_dataset <- merge(x = final_country_dataset, y = tempdataset14, by = c("Year", "variable"), all = TRUE)

final_country_dataset <- final_country_dataset %>% rename(Pays=variable)
```

## Visualisation rapide des données
```{r}
head(final_region_dataset)
```
```{r}
head(final_country_dataset)
```

```{r}
final_region_dataset %>% filter(Region == "World") %>%
ggplot(aes(x=Year))+geom_line(aes(y=PTNIT1_in_percent, color="Top 1%"))+geom_line(aes(y=PTNIB50_in_percent, color="Bot 50%")) + labs(title="Evolution de la part du revenu national des Top 1% et Bot 50% de 1980 à 2019", x="Années", y = "Part du revenu national (%)",color = "Classes" )+ scale_x_continuous(limits = c(1980,2019), expand = c(0, 0)) + scale_y_continuous(limits = c(5,25), expand = c(0, 0))
```
```{r}
world <- filter(final_region_dataset, Region== "World")
world <- melt(world[,c('Year','PTNIT10_in_percent','PTNIM40_in_percent','PTNIB50_in_percent')],id.vars =1)

world%>%
ggplot(aes(x=Year))+geom_col(aes(y=value, fill=variable))+ scale_fill_discrete(name = "Classes", labels = c("Top 10%", "Mid 40%", "Bot 50%"))+
labs(title="Evolution de la part de chaque tranche dans le revenu national dans le monde", x="Années", y = "Part du revenu national (%)" )+
theme(axis.text.y=element_blank(),
      axis.ticks.y=element_blank())
```

```{r message = FALSE, warning = FALSE}
final_region_dataset %>% 
filter(Region=="World") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) %>%
ggplot(aes(x = Year, y = Percent_Change)) + geom_line() + geom_smooth()+ labs(title="Evolution du taux de croissance du National Income dans le monde", x="Années", y = "Taux de croissance NI")
```



```{r message = FALSE, warning = FALSE}
final_region_dataset %>% 
filter(Region=="Eastern Europe") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempEE
final_region_dataset %>% 
filter(Region=="Western Europe") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempWE
final_region_dataset %>% 
filter(Region=="Asia") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempAs
final_region_dataset %>% 
filter(Region=="Africa") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempAf
final_region_dataset %>% 
filter(Region=="Oceania") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempOc
final_region_dataset %>% 
filter(Region=="Latin America") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempLA
final_region_dataset %>% 
filter(Region=="Northern America") %>%
mutate(Previous_Year = lag(NI, 1), Change = NI - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempNA

ggplot(NULL, aes(x = Year, y = Percent_Change)) + geom_smooth(data=tempEE, aes(color="Eastern Europe"), se = FALSE)+ geom_smooth(data=tempWE, aes(color="Western Europe"), se = FALSE)+ geom_smooth(data=tempAs, aes(color="Asia"), se = FALSE)+ geom_smooth(data=tempAf, aes(color="Africa"), se = FALSE)+ geom_smooth(data=tempOc, aes(color="Oceania"), se = FALSE)+ geom_smooth(data=tempLA, aes(color="Latin America"), se = FALSE)+ geom_smooth(data=tempNA, aes(color="Northern America"), se = FALSE)+ labs(title="Evolution du taux de croissance du National Income", x="Années", y = "Taux de croissance NI",color = "Régions" )
```
```{r message = FALSE, warning = FALSE}
final_region_dataset %>% 
filter(Region=="World") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) %>%
ggplot(aes(x = Year, y = Percent_Change)) + geom_line() + geom_smooth()+ labs(title="Evolution du taux de l'enrichissement des Top 1% dans le monde", x="Années", y = "Taux de croissance de la part dans le revenu nationa")
```

```{r  message = FALSE, warning = FALSE}
final_region_dataset %>% 
filter(Region=="Eastern Europe") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempEE
final_region_dataset %>% 
filter(Region=="Western Europe") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempWE
final_region_dataset %>% 
filter(Region=="Asia") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempAs
final_region_dataset %>% 
filter(Region=="Africa") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempAf
final_region_dataset %>% 
filter(Region=="Oceania") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempOc
final_region_dataset %>% 
filter(Region=="Latin America") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempLA
final_region_dataset %>% 
filter(Region=="Northern America") %>%
mutate(Previous_Year = lag(PTNIT1_in_percent, 1), Change = PTNIT1_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempNA

ggplot(NULL, aes(x = Year, y = Percent_Change)) + geom_smooth(data=tempEE, aes(color="Eastern Europe"), se = FALSE)+ geom_smooth(data=tempWE, aes(color="Western Europe"), se = FALSE)+ geom_smooth(data=tempAs, aes(color="Asia"), se = FALSE)+ geom_smooth(data=tempAf, aes(color="Africa"), se = FALSE)+ geom_smooth(data=tempOc, aes(color="Oceania"), se = FALSE)+ geom_smooth(data=tempLA, aes(color="Latin America"), se = FALSE)+ geom_smooth(data=tempNA, aes(color="Northern America"), se = FALSE)+ labs(title="Evolution du taux de croissance de l'enrichissement des Top 1%", x="Années", y = "Taux de croissance de la part dans le revenu national",color = "Régions" )
```
```{r message = FALSE, warning = FALSE}
final_region_dataset %>% 
filter(Region=="World") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) %>%
ggplot(aes(x = Year, y = Percent_Change)) + geom_line() + geom_smooth()+ labs(title="Evolution du taux de l'enrichissement des Bottom 50% dans le monde", x="Années", y = "Taux de croissance de la part dans le revenu nationa")
```

```{r message = FALSE, warning = FALSE}
final_region_dataset %>% 
filter(Region=="Eastern Europe") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempEE
final_region_dataset %>% 
filter(Region=="Western Europe") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempWE
final_region_dataset %>% 
filter(Region=="Asia") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempAs
final_region_dataset %>% 
filter(Region=="Africa") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempAf
final_region_dataset %>% 
filter(Region=="Oceania") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempOc
final_region_dataset %>% 
filter(Region=="Latin America") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempLA
final_region_dataset %>% 
filter(Region=="Northern America") %>%
mutate(Previous_Year = lag(PTNIB50_in_percent, 1), Change = PTNIB50_in_percent - Previous_Year, Percent_Change = Change/Previous_Year*100) -> tempNA

ggplot(NULL, aes(x = Year, y = Percent_Change)) + geom_smooth(data=tempEE, aes(color="Eastern Europe"), se = FALSE)+ geom_smooth(data=tempWE, aes(color="Western Europe"), se = FALSE)+ geom_smooth(data=tempAs, aes(color="Asia"), se = FALSE)+ geom_smooth(data=tempAf, aes(color="Africa"), se = FALSE)+ geom_smooth(data=tempOc, aes(color="Oceania"), se = FALSE)+ geom_smooth(data=tempLA, aes(color="Latin America"), se = FALSE)+ geom_smooth(data=tempNA, aes(color="Northern America"), se = FALSE)+ labs(title="Evolution du taux de croissance de l'enrichissement des Bottom 50%", x="Années", y = "Taux de croissance de la part dans le revenu national",color = "Régions" )
```